Exercise

What Needs to be done?

1. To build a Linear Regressor to predict HOusing Prices for Boston
2. Use Tensorflow to build a Linear Regressor Model

What is given?
1. Housing prices data
2. 13 features and price

Load Tensorflow


In [1]:
# MAke sure Tensorflow 2.x is installed
!pip install -U Tensorflow==2.0.0 --quiet

     |████████████████████████████████| 86.3MB 70kB/s 
     |████████████████████████████████| 3.8MB 35.8MB/s 
     |████████████████████████████████| 450kB 37.5MB/s 
     |████████████████████████████████| 81kB 11.5MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.11.0 which is incompatible.


In [2]:
import tensorflow as tf
tf.__version__

'2.0.0'

Load Data

In [3]:
#Load Boston Housing data available within tensorflow
# We get the data as NumpyArray
(train_x, train_y),(_,_) = tf.keras.datasets.boston_housing.load_data(test_split=0)

57344/57026 [==============================] - 0s 0us/step


In [4]:
#Check the number of training samples
train_x.shape

(506, 13)

In [0]:
# Machine learning is about building logic using data and math

In [6]:
train_x.dtype

dtype('float64')

In [0]:
# Each floating point is stored in 64 bits of memory. 8 bytes. Numpy uses float64 as default notation
# In tf, float 32 is used. to reduce memory requirement
# convert the datatype as float32 (8 bytes to 4 bytes)
#
train_x = train_x.astype('float32')
train_y =train_y.astype('float32')

In [8]:
train_x[0:5]

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        6.14200e+00, 9.17000e+01, 3.97690e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, 0.00000e+00, 4.15000e-01,
        7.61000e+00, 1.57000e+01, 6.27000e+00, 2.00000e+00, 3.48000e+02,
        1.47000e+01, 3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
        4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.75520e+02, 3.26000e+00],
       [3.96100e-02, 0.00000e+00, 5.19000e+00, 0.00000e+00, 5.15000e-01,
        6.03700e+00, 3.45000e+01, 5.98530e+00, 5.00000e+00, 2.24000e+02,
        2.02000e+01, 3.96900e+02, 8.01000e+00],
       [3.69311e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.13000e-01,
        6.37600e+00, 8.84000e+01, 2.56710e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.91430e+02, 1.46500e+01]], dtype=float32)

In [9]:
train_y.shape

(506,)

Normalize Input features


In [11]:
from sklearn.preprocessing import Normalizer
transformer= Normalizer()
train_x = transformer.fit_transform(train_x)
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945358, 0.00778265, 0.00782786, 0.60078794,
       0.04109624, 0.776719  , 0.03663436], dtype=float32)

Build Model

Define Weights and Bias

In [0]:
#Initializing the weights and bias with 0
w= tf.zeros(shape=(13,1))
b= tf.zeros(shape=(1))

Define a function to calculate prediction

In [0]:
def prediction(x,w,b):

  xw_matmul=tf.matmul(x,w)
  y = tf.add(xw_matmul,b)

  return y

Function to calculate Loss (Mean Squared Error)

In [0]:
def loss(y_actual, y_predicted):
  
  diff = y_actual - y_predicted
  sqr = tf.square(diff)
  avg = tf.reduce_mean(sqr)

  return avg

Function to train the model


1. Record all the mathematical steps to calculate Loss, We shall record the steps using Gradient tape

2. Calculate Gradients of Loss w.r.t weights and bias

3. Update weights and bias based on gradients and learning rate

Function to Train the model

In [0]:
def train(x, y_actual,w,b, learning_rate=0.01):
  
  #Record mathematical operations on 'tape' to calculate loss
  with tf.GradientTape() as gradientTape: 

    gradientTape.watch([w,b])

    current_prediction = prediction(x,w,b)
    current_loss = loss(y_actual, current_prediction)

  #Calculate Gradients for Loss with respect to weights and Bia
  dw,db = gradientTape.gradient(current_loss,[w,b])

  #Update weights and bias
  w=w-learning_rate*dw
  b=b-learning_rate*db

  return w, b

Start Training

In [16]:
#Train for 100 Steps : Model.fit
for i in range(100):
    w , b = train(train_x, train_y,w,b, learning_rate=0.01)
    print('Current Loss on iteration', i, loss(train_y, prediction(train_x,w,b)).numpy())

Current Loss on iteration 0 553.7515
Current Loss on iteration 1 518.26166
Current Loss on iteration 2 485.45786
Current Loss on iteration 3 455.13657
Current Loss on iteration 4 427.10983
Current Loss on iteration 5 401.20413
Current Loss on iteration 6 377.25894
Current Loss on iteration 7 355.12595
Current Loss on iteration 8 334.66785
Current Loss on iteration 9 315.75797
Current Loss on iteration 10 298.27924
Current Loss on iteration 11 282.1232
Current Loss on iteration 12 267.1898
Current Loss on iteration 13 253.38655
Current Loss on iteration 14 240.62785
Current Loss on iteration 15 228.83476
Current Loss on iteration 16 217.93404
Current Loss on iteration 17 207.85832
Current Loss on iteration 18 198.54506
Current Loss on iteration 19 189.9366
Current Loss on iteration 20 181.9796
Current Loss on iteration 21 174.62473
Current Loss on iteration 22 167.82646
Current Loss on iteration 23 161.54263
Current Loss on iteration 24 155.73434
Current Loss on iteration 25 150.36557
C

In [17]:
#Check Weights and Bias
print('Weights: \n', w.numpy())
print('Bias: \n', b.numpy())

Weights: 
 [[6.27857521e-02]
 [2.58572161e-01]
 [2.17821732e-01]
 [1.46146421e-03]
 [1.13587305e-02]
 [1.31812572e-01]
 [1.38818812e+00]
 [8.23873580e-02]
 [1.76484972e-01]
 [7.99328279e+00]
 [3.82081836e-01]
 [7.41107655e+00]
 [2.53885090e-01]]
Bias: 
 [11.476417]


In [18]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945358, 0.00778265, 0.00782786, 0.60078794,
       0.04109624, 0.776719  , 0.03663436], dtype=float32)